### ISSUE TITLE
Linked resources block doesn't show all linked resources

### ISSUE THREAD

**Issue by smartz0529** [omeka-s-themes/freedom#10]
On item pages, linked resources block displays only first 25 items. If an item has linked resources of various relationships (items with "creator:", items with "references:"), those relationships are omitted if the first relationship displayed has more than 25 linked resources.

**Comment by nelsonamaya82** [comment]
@smartz0529 thanks for reporting this issue. I'm working on a fix now.

**Comment by nelsonamaya82** [comment]
@smartz0529 this issue is fixed now and will be included in the next release.

**Comment by smartz0529** [comment]
thanks you!
