### ISSUE TITLE
Item Carousel display

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/freedom#13]
With 4.1, the item carousel block can have any colour background. The little feature-colour line under the item title looks nice, but the rest of the light grey line can look odd depending on the background chosen. It's very small in the attached images, but if you look close you'll see what I mean. 

I think you can just remove the border-bottom setting and it looks fine. Maybe also add padding-top:1rem to the caption underneath it, to match the spacing above and below. 

<img width="1125" alt="Screenshot 2024-03-13 at 19 06 25" src="https://github.com/omeka-s-themes/freedom/assets/28012148/3e69ce92-b23d-4468-9987-deedc654cc84">

<img width="1123" alt="Screenshot 2024-03-13 at 19 06 35" src="https://github.com/omeka-s-themes/freedom/assets/28012148/a6297ed5-8a9c-4884-b600-df4f1bf10463">

This is a `.title` style, so it applies to page titles as well - it's up to you if you want to remove that line for all titles or just specify a little more in the CSS.

**Comment by nelsonamaya82** [comment]
@allanaaa actually this underline decoration is not intended to be used on this type of titles, so I removed it from Item Carousel block titles.
