### ISSUE TITLE
Code Displaying in Item Titles

### ISSUE THREAD

**Issue by smartz0529** [omeka-s-themes/freedom#15]
When displaying item sets in browse preview on a page, code for ampersands and quotes displaying in item title. Code does not display on other pages such as results from advanced search.

![Browse Preview Item Set Ampersand and Quotes FreedomTheme](https://github.com/omeka-s-themes/freedom/assets/137115844/6d73ac64-0f8e-4a35-94e6-2b99c51a048b)

**Comment by smartz0529** [comment]
Apologies if these issues have arisen from user error -- still relatively new to Omeka.

**Comment by nelsonamaya82** [comment]
@smartz0529 thanks for reporting this issue. I've just splitted it into 2 different issues, one the code displaying in titles (this same issue) and the one related to the "See More" Non-Functioning on Faceted Browse here: https://github.com/omeka-s-themes/freedom/issues/19

**Comment by smartz0529** [comment]
Thank you for this fix!
