### ISSUE TITLE
Facets not showing on mobile version

### ISSUE THREAD

**Issue by fmadore** [omeka-s-themes/freedom#18]
I'm using the latest version of the theme and the Faceted Browse module, version 1.4.1. The facets do not appear on the mobile version of the site. There's only the "Copy permalink" button. I'm using Omeka S version 4.0.4.

**Comment by nelsonamaya82** [comment]
@fmadore thanks for reporting this issue, I've just fixed it and it's already merged into the [master](https://github.com/omeka-s-themes/freedom) branch and will be included in the next release. In the meantime, you can download a copy of the master branch and test it.

Please let me know if it works for you.

**Comment by nelsonamaya82** [comment]
Fix already included in the [Latest Release](https://github.com/omeka-s-themes/freedom/releases/tag/v1.0.4)
