### ISSUE TITLE
"See More" Non-Functioning on Faceted Browse

### ISSUE THREAD

**Issue by nelsonamaya82** [omeka-s-themes/freedom#19]
When using the Faceted Browse module and attempting to truncate values on a facet, public-facing page does truncate values, but clicking "See More" does not expand list of facets.
![image](https://github.com/omeka-s-themes/freedom/assets/6953921/84a79fd5-9f3b-4680-a5bc-80925f9144f6)
![image](https://github.com/omeka-s-themes/freedom/assets/6953921/3ebdfc71-6607-4a5a-9c01-415930f3ae04)

**Comment by nelsonamaya82** [comment]
@smartz0529 thanks for reporting this issue, I've just fixed it and it's already merged into the [master](https://github.com/omeka-s-themes/freedom) branch and will be included in the next release. In the meantime, you can download a copy of the master branch and test it. Also make sure you're using the latest version of the [Faceted Browse](https://omeka.org/s/docs/user-manual/modules/facetedbrowse/) module (1.4.1).

Please let me know if it works for you.

**Comment by nelsonamaya82** [comment]
Fix already included in the [Latest Release](https://github.com/omeka-s-themes/freedom/releases/tag/v1.0.4)

**Comment by smartz0529** [comment]
Works perfectly, thank you!
