### ISSUE TITLE
$decorationClass variable unset in browse-preview partial

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-themes/freedom#2]
> Warning: Undefined variable $decorationClass in /var/www/html/omeka-s/themes/freedom/view/common/block-layout/browse-preview.phtml on line 58

This looks to be something that's repeated across the various browse pages, but in browse-preview it lacks the code that actually sets it to anything. Not sure if the intent here is to have it set like in the other locations, or just remove it entirely.

**Comment by nelsonamaya82** [comment]
Thanks @zerocrates, I've just fixed it and it's merged into the [master](https://github.com/omeka-s-themes/freedom) branch.
