### ISSUE TITLE
Hyperlinks invisible in Footer Site description, Footer Content, and Footer Copyright sections

### ISSUE THREAD

**Issue by jbhistorian** [omeka-s-themes/freedom#21]
I have added a couple of hyperlinks in the Footer Site description section of the theme, like so:
<img width="1121" alt="image" src="https://github.com/omeka-s-themes/freedom/assets/89092402/775cd12c-21cd-4944-93f4-3af763a7d8d7">

The result is this:
![image](https://github.com/omeka-s-themes/freedom/assets/89092402/ddcf2df9-89d4-439e-9f31-9573b1d9acf4)

The links that are part of the Footer Menu section are visible, but hyperlinks in the Footer Site description section are hidden because they default to the same color as the footer background. I had the same result when testing hyperlinks in the Footer Content and Footer Copyright sections.

I manually set the hyperlink color to white on my website, but I thought I should flag this for you in case you want to change the hyperlink styling for the footer at the theme level.

**Comment by nelsonamaya82** [comment]
@jbhistorian thanks for reporting this issue. It's fixed now in the [master](https://github.com/omeka-s-themes/freedom) branch and will be included in the next theme release.
