### ISSUE TITLE
Issue with display errors for deleted items

### ISSUE THREAD

**Issue by cynthialeng** [omeka-s-themes/freedom#23]
Hi,

I'm encountering an issue where the page displays "Omeka S encountered an error" when an item previously showcased using the "Item with metadata" and "Item carousel" is deleted. The error log shows: "Error: Call to a member function primaryMedia() on null in /home/japnsit1/mapping.japn.sites.carleton.edu/themes/freedom/view/common/block-layout/item-with-metadata.phtml:11". However, "Universal Viewer", "Browse preview", and "Media embed" work correctly.

Is it possible to make this process automatic so that, if an item is deleted in the future, the pages that include it will still load normally? 

Thanks!

<img width="983" alt="error" src="https://github.com/omeka-s-themes/freedom/assets/144724682/ff538d78-8529-4db9-9a05-fb63e522e767">

**Comment by nelsonamaya82** [comment]
Hi @cynthialeng, thanks for reporting this issue. We're looking at this now and will update this ticket as soon as it's fixed.

**Comment by nelsonamaya82** [comment]
@cynthialeng this issue is fixed now in the [master](https://github.com/omeka-s-themes/freedom) branch and will be included in the next theme release. Thanks!

**Comment by nelsonamaya82** [comment]
@cynthialeng the issue in the "Item carousel" block is fixed in the [block's repository](https://github.com/omeka-s-modules/ItemCarouselBlock) directly but we need to release a new version including this fix. Will check this with the team.
