### ISSUE TITLE
"Thumbnail only" media embed block option broken in 4.1.0

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-themes/freedom#24]
Freedom includes its own copy of the common/block-layout/file.phtml view used for the media embed block.

We made a fix late in the 4.1 cycle to the new media block feature for forcing thumbnails instead of media embeds (this is used when upgrading from merged showcase blocks but also the user can select it). Freedom's copy of this view doesn't have the updated code used to display thumbnails when this setting is enabled, leading to incorrect behavior.

Here's the relevant core change: https://github.com/omeka/omeka-s/commit/04f63ff4848cbb5cee6b1c1a4fc654f2f24e5927#diff-2922c840ce26bb97ddd6689b705c80ca63565b2b96175be885106167601124c9

You'll only notice the difference when using media that have a non-image embed (videos, audio, IIIF images or presentations, etc.)

See this report from the forums: https://forum.omeka.org/t/mirador-viewer-issue/22601

**Comment by nelsonamaya82** [comment]
Thanks for reporting this issue. It's fixed now in the [master](https://github.com/omeka-s-themes/freedom) branch and will be included in the next theme release.
