### ISSUE TITLE
Empty property labels displaying

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/freedom#3]
Re: https://github.com/omeka/omeka-s/issues/2070#issuecomment-1650351929

Core is fixed and all the other themes are hiding empty properties, just this one left.

**Comment by nelsonamaya82** [comment]
Thanks @allanaaa, this is fixed now and merged into the [master](https://github.com/omeka-s-themes/freedom) branch.

Please let me know if it works on your end.
