### ISSUE TITLE
Advanced search with several values: Only last value is used

### ISSUE THREAD

**Issue by mnhampl** [omeka-s-themes/freedom#5]
I'm trying out Omeka S for the first time. Very nice theme -- although it seems to have one or two bugs. 

When I try to combine two values in advanced search (title contains 'a' and title contains 'b') only title contains 'b' is searched for:

![advanced_search](https://github.com/omeka-s-themes/freedom/assets/53606837/490cae98-9377-4a7a-b4cb-45df3e5ea09a)

![result](https://github.com/omeka-s-themes/freedom/assets/53606837/899ca2f9-491a-4016-8ae5-69dc5243fcda)

The URL I get is
http://localhost/omeka-s/s/lca/item?property[0][joiner]=and&property[0][property]=1&property[0][type]=eq&property[0][text]=a&property[0][joiner]=and&property[0][property]=1&property[0][type]=eq&property[0][text]=b&submit=Search
so the reason seems to be that both properties get the index 0 and so the first property is overwritten by the second. 

I have this behavior with two different installations. If I'm doing something wrong I don't know what it could be. It works when I switch to the default theme.

**Comment by nelsonamaya82** [comment]
Hi @mnhampl,

Thanks for reporting this issue, we are working on a fix now and will update this thread as soon as it's resolved.

**Comment by nelsonamaya82** [comment]
@mnhampl this issue is fixed now and merged into the [master](https://github.com/omeka-s-themes/freedom) branch. Could you please pull the latest version from master and let me know if it works for you now?

**Comment by mnhampl** [comment]
@nelsonamaya82 I tested it and works for me. Thanks a lot :)
