### ISSUE TITLE
Lightbox gallery: Partly hidden by site header when maximized

### ISSUE THREAD

**Issue by mnhampl** [omeka-s-themes/freedom#6]
I'm using the lightbox gallery at the top of the main region of the page for the display of media files. When I maximize it the top gets covered by the site header. That also hides the controls (rotate, zoom, download, minimize) in the top right corner of the gallery.

Before maximization:
![lightbox_gallery_minimized](https://github.com/omeka-s-themes/freedom/assets/53606837/70ad102c-3866-47e8-8268-59db924073a6)

Maximized
![lightbox_gallery](https://github.com/omeka-s-themes/freedom/assets/53606837/2dc4b97c-fdd5-40a1-af1e-db809ee94287)

**Comment by mnhampl** [comment]
I think this is the same issue that's described here: https://github.com/omeka/omeka-s/issues/2114
Is there a way to connect these two issues?

**Comment by joebauer** [comment]
> I think this is the same issue that's described here: [omeka/omeka-s#2114](https://github.com/omeka/omeka-s/issues/2114) Is there a way to connect these two issues?

yes, this is the same issue that we are seeing - thanks for merging these.

**Comment by nelsonamaya82** [comment]
Thanks @mnhampl and @joebauer for reporting this issue. I'm working on it now and will update this thread as soon as it's fixed.

**Comment by nelsonamaya82** [comment]
@mnhampl @joebauer this is fixed now and available in the [master](https://github.com/omeka-s-themes/freedom) branch.
