### ISSUE TITLE
Can't scroll all the way down on long hamburger navigation on mobile view

### ISSUE THREAD

**Issue by GitByrd** [omeka-s-themes/freedom#8]
We are using this theme for our exhibitions, and I just noticed on some of our exhibit sites that have many navigation items, that we can't scroll all the way down while in mobile view. 

For example, here's a test site that has several top navigation pages...but while viewing the site on my phone, I can only scroll down so much on the page and I can't see all of the option. 

https://dev.schafferlibrarycollections.org/s/the-flight-and-return-of-the-audubons

**Comment by nelsonamaya82** [comment]
Hi @GitByrd, I'm testing it on a dev environment and it works fine, but adding some padding to the bottom of the menu container might work, I'll do it and will keep you posted. In the meantime, could you enable your test page again please?

Thanks.

**Comment by GitByrd** [comment]
@nelsonamaya82 Thank you so much for looking into this. I just updated the link, I recreate the issue on another instance.

**Comment by GitByrd** [comment]
Hi, just following up. I have been experimenting with title lengths, and reducing the font size for mobile view in order to compensate for several tier 1 navigation items. Also, in my live instance, I increased the max-width from 50% to 75% for the .main-header__site-title CSS rule for small mobile widths, again in order to compensate. I think our institution sometimes has long two-part titles and also many navigation items, which causes the scrolling issue. I will advise content creators to keep both titles and tier 1 navigation list on the shorter side, to make better use of nesting menu items. Thanks!

**Comment by nelsonamaya82** [comment]
Thanks @GitByrd, I've just pushed a fix for this to the [master](https://github.com/omeka-s-themes/freedom) branch and will be included in the next release.
